name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Build-Project-Linux:
      name: Build Project on Linux
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
        - run: cmake -H. -B_build
        - run: cmake --build _build
        - name: Configure and Build Project
          uses: threeal/cmake-action@v1.3.0
  Build-Project-Windows:
        name: Build Project on Windows
        runs-on: windows-latest
        steps:
          - name: Checkout
            uses: actions/checkout@v4
          - run: cmake -H. -B_build
          - run: cmake --build _build
          - name: Configure and Build Project
            uses: threeal/cmake-action@v1.3.0

